name: Continuous Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  deploy:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: atlas
          POSTGRES_PASSWORD: 7265
          POSTGRES_DB: mydb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12    
      - run: npm ci
      - run: npx db-migrate up
      - run: npm test
      - run: npm run build
      - run: cp -r build/* /var/www/43.205.78.4/