name: Production Rollback

on: 
  release:
    types: [ deleted ]

jobs:
  deploy:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: atlas
          POSTGRES_PASSWORD: 7265
          POSTGRES_DB: mydb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - id: latest
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.TEST_TOKEN }}
      - uses: actions/checkout@master
        with: 
          ref: ${{ steps.latest.outputs.tag_name }}
      - uses: actions/setup-node@master
        with:
          node-version: 12    
      - run: npm ci
      - run: npx db-migrate down
      - run: npm test
      - run: npm run build
      - run: cp -r build/* /var/www/43.205.78.4/