name: Testing Commits

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  deploy:
    runs-on: self-hosted
    
    steps:      
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12    
      - run: npm ci
      - run: npm test
